### ISSUE TITLE
Add Get and Post methods to Program.cs

### ISSUE THREAD

**Issue by SOBIGARANI** [VaclavElias/Emsi#10]
- GetVersionsAsync()
- GetVersionAsync(string version)
- GetChangesAsync(string version)
- GetRelatedAsync(List<string> ids) 
  - this one has rate limit in place
- GetSkillsAndTraceFromDocumentAsync(string version) from ../extract/trace endpoint

**Comment by VaclavElias** [comment]
This is now done. Closing.
