### ISSUE TITLE
Create Playground Tasks

### ISSUE THREAD

**Issue by VaclavElias** [VaclavElias/Emsi#9]
Create 2 tasks from the below, verify and assign them to Mohan and Sobi, add any additional comments to the tasks.

Add Get and Post Methods to Program.cs

**Mogan**
- GetVersionsAsync()
- GetVersionAsync(string version)
- GetChangesAsync(string version)
- GetRelatedAsync(List<string> ids) 
  - this one has rate limit in place
- GetSkillsAndTraceFromDocumentAsync(string version) from ../extract/trace endpoint 

**Sobi**
- GetSkillsAsync(string version) 
  - don't worry about typeIds, fields, limit in the query for now
- GetSkillsAsync(List<string> ids)
  - don't worry about typeIds, fields, limit in the query for now
- GetSkillAsync(string version, string id)
- GetSkillsFromDocumentAsync(string version) from ../extract endpoint

**Comment by SOBIGARANI** [comment]
Playground tasks created and assigned. This is done.
